# Generated by Django 4.2.1 on 2023-05-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OOPs_Concept', '0002_place_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='pizza',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='soups',
            field=models.BooleanField(default=False),
        ),
    ]
