# Generated by Django 4.2.1 on 2023-06-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('staff', 'staff'), ('student', 'student')], max_length=10)),
                ('contact', models.IntegerField(default=0)),
                ('gender', models.BooleanField(choices=[('male', 'male'), ('female', 'female')])),
                ('attendance', models.BooleanField(choices=[('present', 'present'), ('absent', 'absent'), ('leave', 'leave')])),
            ],
        ),
    ]
