# Generated by Django 4.2.1 on 2023-06-16 11:32

from django.db import migrations, models
import user_profile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('roll_no', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('country', models.CharField(blank=True, max_length=30)),
                ('contact', models.CharField(blank=True, max_length=15)),
                ('gender', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=30)),
                ('st_img', models.ImageField(blank=True, default=user_profile.models.get_default_image, upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('date_of_birth', models.DateField(blank=True)),
                ('address', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(blank=True, choices=[('admin', 'admin'), ('staff', 'staff'), ('student', 'student')], max_length=10)),
                ('contact', models.CharField(blank=True, max_length=15)),
                ('gender', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('attendance', models.CharField(blank=True, choices=[('present', 'present'), ('absent', 'absent'), ('leave', 'leave')], max_length=10)),
                ('user_img', models.ImageField(blank=True, default=user_profile.models.get_default_image, upload_to='uploads/')),
            ],
        ),
    ]
