# Generated by Django 4.2.1 on 2023-06-05 08:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_alter_userprofile_attendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='static/images'),
            preserve_default=False,
        ),
    ]
