# Generated by Django 4.2.1 on 2023-06-06 20:56

from django.db import migrations, models
import user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_alter_userprofile_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_img',
            field=models.ImageField(default=user_profile.models.get_default_image, upload_to='media/images/'),
        ),
    ]
