# Generated by Django 4.2.1 on 2023-06-07 12:05

from django.db import migrations, models
import user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='st_img',
            field=models.ImageField(blank=True, default=user_profile.models.get_default_image, upload_to='static/media/images/'),
        ),
    ]
